version: '3.9'
services:
  bronze-db:
    image: postgres:latest
    container_name: bronze-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${BRONZE_DB}
    ports:
      - "5433:5432"
    volumes:
      - bronze_data:/var/lib/postgresql/data

  silver-db:
    image: postgres:latest
    container_name: silver-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${SILVER_DB}
    ports:
      - "5434:5432"
    volumes:
      - silver_data:/var/lib/postgresql/data

  gold-db:
    image: postgres:latest
    container_name: gold-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${GOLD_DB}
    ports:
      - "5435:5432"
    volumes:
      - gold_data:/var/lib/postgresql/data


# Test databases for CI  
  test-bronze-db:
    image: postgres:15
    container_name: test-bronze-db
    profiles: [test]
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_BRONZE_DB}
    ports:
      - "6433:5432"
    volumes:
      - test_bronze_data:/var/lib/postgresql/data

  test-silver-db:
    image: postgres:15
    container_name: test-silver-db
    profiles: [test]
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_SILVER_DB}
    ports:
      - "6434:5432"
    volumes:
      - test_silver_data:/var/lib/postgresql/data

  test-gold-db:
    image: postgres:15
    container_name: test-gold-db
    profiles: [test]
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_GOLD_DB}
    ports:
      - "6435:5432"
    volumes:
      - test_gold_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: novacancy-app
    depends_on:
      - bronze-db
      - silver-db
      - gold-db
    env_file:
      - .env
    environment:
      # General app configuration
      DATA_DIR: ./data

      # Bronze DB
      BRONZE_DB_HOST: bronze-db
      BRONZE_DB_PORT: ${BRONZE_DB_PORT}
      BRONZE_DB_NAME: ${BRONZE_DB}
      BRONZE_DB_USER: ${DB_USER}
      BRONZE_DB_PASSWORD: ${DB_PASSWORD}
      BRONZE_TABLE: raw_data

      # Silver DB
      SILVER_DB_HOST: silver-db
      SILVER_DB_PORT: ${SILVER_DB_PORT}
      SILVER_DB_NAME: ${SILVER_DB}
      SILVER_DB_USER: ${DB_USER}
      SILVER_DB_PASSWORD: ${DB_PASSWORD}
      SILVER_TRAIN_TABLE: train_data
      SILVER_VALIDATION_TEST_TABLE: validation_test_data

      # Gold DB
      GOLD_DB_HOST: gold-db
      GOLD_DB_PORT: ${GOLD_DB_PORT}
      GOLD_DB_NAME: ${GOLD_DB}
      GOLD_DB_USER: ${DB_USER}
      GOLD_DB_PASSWORD: ${DB_PASSWORD}
      GOLD_TRAIN_TABLE: train_results
      GOLD_VALIDATION_TABLE: validation_results
      GOLD_TEST_TABLE: test_results

    # volumes:
      # - .:/app
    command: python scripts/import_csv_to_postgres.py

volumes:
  bronze_data:
  silver_data:
  gold_data:
  test_bronze_data:
  test_silver_data:
  test_gold_data:
