version: '3.9'
services:
  bronze-db:
    image: postgres:latest
    container_name: bronze-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${BRONZE_DB}
    ports:
      - "5433:5432"
    volumes:
      - bronze_data:/var/lib/postgresql/data

  silver-db:
    image: postgres:latest
    container_name: silver-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${SILVER_DB}
    ports:
      - "5434:5432"
    volumes:
      - silver_data:/var/lib/postgresql/data

  gold-db:
    image: postgres:latest
    container_name: gold-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${GOLD_DB}
    ports:
      - "5435:5432"
    volumes:
      - gold_data:/var/lib/postgresql/data


# Test databases for CI  
  test-bronze-db:
    image: postgres:15
    container_name: test-bronze-db
    env_file:
      - .env.ci
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_BRONZE_DB}
    ports:
      - "6543:5432"
    volumes:
      - test_bronze_data:/var/lib/postgresql/data

  test-silver-db:
    image: postgres:15
    container_name: test-silver-db
    env_file:
      - .env.ci
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_SILVER_DB}
    ports:
      - "6544:5432"
    volumes:
      - test_silver_data:/var/lib/postgresql/data

  test-gold-db:
    image: postgres:15
    container_name: test-gold-db
    env_file:
      - .env.ci
    environment:
      POSTGRES_USER: ${TEST_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_GOLD_DB}
    ports:
      - "6545:5432"
    volumes:
      - test_gold_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: novacancy-app
    depends_on:
      - bronze-db
      - silver-db
      - gold-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATA_DIR: ./data
      BRONZE_TABLE: raw_data
      SILVER_TRAIN_TABLE: train_data
      SILVER_VALIDATION_TEST_TABLE: validation_test_data
      GOLD_TRAIN_TABLE: train_results
      GOLD_VALIDATION_TABLE: validation_results
      GOLD_TEST_TABLE: test_results
    volumes:
      - .:/app
    command: python scripts/import_csv_to_postgres.py

volumes:
  bronze_data:
  silver_data:
  gold_data:
  test_bronze_data:
  test_silver_data:
  test_gold_data:
