# Container setup for model training
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app/ .

# TODO: Change when Airflow is added
CMD ["python", "services/training_orchestrator.py"]
