version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    container_name: test-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5433:5432" # Host 5433 -> Container 5432 to  avoid conflict with the main db


  app:
    build: .
    container_name: novacancy-app
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: novacancy_user
      POSTGRES_PASSWORD: penthousesuite
      POSTGRES_DB: novacancy
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATA_DIR: ./data/raw
      TRAIN_TABLE: train_table
      VALIDATION_TABLE: validation_table
      TEST_TABLE: test_table
    volumes:
      - .:/app
    command: python scripts/import_csv_to_postgres.py

volumes:
  db_data:
