# Container setup for MLflow
# Set the version for reproducibility. Critical for CD pipeline.
FROM ghcr.io/mlflow/mlflow:v2.14.3

# MLflow requires the git binary to log the Git SHA
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

# Required for MLflow Postgres DB
RUN pip install psycopg2-binary
