from sqlalchemy import Column, Integer, String, Float, Date
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class TrainData(Base):
    __tablename__ = "train_data"

    booking_id = Column(String, primary_key=True)
    number_of_adults = Column(Integer, nullable=False)
    number_of_children = Column(Integer, nullable=False)
    number_of_weekend_nights = Column(Integer, nullable=False)
    number_of_weekdays_nights = Column(Integer, nullable=False)
    lead_time = Column(Integer, nullable=False)  # in days
    type_of_meal = Column(String, nullable=False)
    car_parking_space = Column(Integer, nullable=False)
    room_type = Column(String, nullable=False)
    average_price = Column(Float, nullable=False)
    is_type_of_meal_meal_plan_1 = Column(Integer, nullable=False)
    is_type_of_meal_meal_plan_2 = Column(Integer, nullable=False)
    is_type_of_meal_meal_plan_3 = Column(Integer, nullable=False)
    is_room_type_room_type_1 = Column(Integer, nullable=False)
    is_room_type_room_type_2 = Column(Integer, nullable=False)
    is_room_type_room_type_3 = Column(Integer, nullable=False)
    is_room_type_room_type_4 = Column(Integer, nullable=False)
    is_room_type_room_type_5 = Column(Integer, nullable=False)
    is_room_type_room_type_6 = Column(Integer, nullable=False)
    is_room_type_room_type_7 = Column(Integer, nullable=False)
    is_market_segment_type_online = Column(Integer, nullable=False)
    is_market_segment_type_corporate = Column(Integer, nullable=False)
    is_market_segment_type_complementary = Column(Integer, nullable=False)
    is_market_segment_type_aviation = Column(Integer, nullable=False)
    is_month_of_reservation_nov = Column(Integer, nullable=False)
    is_month_of_reservation_dec = Column(Integer, nullable=False)
    is_month_of_reservation_jun = Column(Integer, nullable=False)
    is_month_of_reservation_jan = Column(Integer, nullable=False)
    is_month_of_reservation_oct = Column(Integer, nullable=False)
    is_month_of_reservation_may = Column(Integer, nullable=False)
    is_month_of_reservation_apr = Column(Integer, nullable=False)
    is_month_of_reservation_aug = Column(Integer, nullable=False)
    is_month_of_reservation_mar = Column(Integer, nullable=False)
    is_month_of_reservation_feb = Column(Integer, nullable=False)
    is_day_of_week_monday = Column(Integer, nullable=False)
    is_day_of_week_friday = Column(Integer, nullable=False)
    is_day_of_week_wednesday = Column(Integer, nullable=False)
    is_day_of_week_thursday = Column(Integer, nullable=False)
    is_day_of_week_saturday = Column(Integer, nullable=False)
    is_day_of_week_tuesday = Column(Integer, nullable=False)
    is_cancellation = Column(Integer, nullable=False)


class ValidationTestData(Base):
    __tablename__ = "validation_test_data"

    booking_id = Column(String, primary_key=True)
    number_of_adults = Column(Integer, nullable=False)
    number_of_children = Column(Integer, nullable=False)
    number_of_weekend_nights = Column(Integer, nullable=False)
    number_of_weekdays_nights = Column(Integer, nullable=False)
    lead_time = Column(Integer, nullable=False)  # in days
    type_of_meal = Column(String, nullable=False)
    car_parking_space = Column(Integer, nullable=False)
    room_type = Column(String, nullable=False)
    average_price = Column(Float, nullable=False)
    is_type_of_meal_meal_plan_1 = Column(Integer, nullable=False)
    is_type_of_meal_meal_plan_2 = Column(Integer, nullable=False)
    is_type_of_meal_meal_plan_3 = Column(Integer, nullable=False)
    is_room_type_room_type_1 = Column(Integer, nullable=False)
    is_room_type_room_type_2 = Column(Integer, nullable=False)
    is_room_type_room_type_3 = Column(Integer, nullable=False)
    is_room_type_room_type_4 = Column(Integer, nullable=False)
    is_room_type_room_type_5 = Column(Integer, nullable=False)
    is_room_type_room_type_6 = Column(Integer, nullable=False)
    is_room_type_room_type_7 = Column(Integer, nullable=False)
    is_market_segment_type_online = Column(Integer, nullable=False)
    is_market_segment_type_corporate = Column(Integer, nullable=False)
    is_market_segment_type_complementary = Column(Integer, nullable=False)
    is_market_segment_type_aviation = Column(Integer, nullable=False)
    is_month_of_reservation_nov = Column(Integer, nullable=False)
    is_month_of_reservation_dec = Column(Integer, nullable=False)
    is_month_of_reservation_jun = Column(Integer, nullable=False)
    is_month_of_reservation_jan = Column(Integer, nullable=False)
    is_month_of_reservation_oct = Column(Integer, nullable=False)
    is_month_of_reservation_may = Column(Integer, nullable=False)
    is_month_of_reservation_apr = Column(Integer, nullable=False)
    is_month_of_reservation_aug = Column(Integer, nullable=False)
    is_month_of_reservation_mar = Column(Integer, nullable=False)
    is_month_of_reservation_feb = Column(Integer, nullable=False)
    is_day_of_week_monday = Column(Integer, nullable=False)
    is_day_of_week_friday = Column(Integer, nullable=False)
    is_day_of_week_wednesday = Column(Integer, nullable=False)
    is_day_of_week_thursday = Column(Integer, nullable=False)
    is_day_of_week_saturday = Column(Integer, nullable=False)
    is_day_of_week_tuesday = Column(Integer, nullable=False)
    is_cancellation = Column(Integer, nullable=False)
