"""baseline for bronze

Revision ID: a88b67d89226
Revises: 
Create Date: 2025-04-23 15:22:22.532209

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a88b67d89226"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_data",
        sa.Column("booking_id", sa.String(), nullable=False),
        sa.Column("number_of_adults", sa.Integer(), nullable=True),
        sa.Column("number_of_children", sa.Integer(), nullable=True),
        sa.Column("number_of_weekend_nights", sa.Integer(), nullable=True),
        sa.Column("number_of_week_nights", sa.Integer(), nullable=True),
        sa.Column("type_of_meal", sa.String(), nullable=True),
        sa.Column("car_parking_space", sa.Integer(), nullable=True),
        sa.Column("room_type", sa.String(), nullable=True),
        sa.Column("lead_time", sa.Integer(), nullable=True),
        sa.Column("market_segment_type", sa.String(), nullable=True),
        sa.Column("is_repeat_guest", sa.Integer(), nullable=True),
        sa.Column("num_previous_cancellations", sa.Integer(), nullable=True),
        sa.Column("num_previous_bookings_not_canceled", sa.Integer(), nullable=True),
        sa.Column("average_price", sa.Float(), nullable=True),
        sa.Column("special_requests", sa.Integer(), nullable=True),
        sa.Column("date_of_reservation", sa.Date(), nullable=True),
        sa.Column("booking_status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_data")
    # ### end Alembic commands ###
