"""baseline silver

Revision ID: 056f3d0a174f
Revises: a88b67d89226
Create Date: 2025-04-23 19:28:07.309776

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "056f3d0a174f"
down_revision: Union[str, None] = "a88b67d89226"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "train_data",
        sa.Column("booking_id", sa.String(), nullable=False),
        sa.Column("number_of_adults", sa.Integer(), nullable=False),
        sa.Column("number_of_children", sa.Integer(), nullable=False),
        sa.Column("number_of_weekend_nights", sa.Integer(), nullable=False),
        sa.Column("number_of_week_nights", sa.Integer(), nullable=False),
        sa.Column("lead_time", sa.Integer(), nullable=False),
        sa.Column("car_parking_space", sa.Integer(), nullable=False),
        sa.Column("is_repeat_guest", sa.Integer(), nullable=False),
        sa.Column("num_previous_cancellations", sa.Integer(), nullable=False),
        sa.Column("num_previous_bookings_not_canceled", sa.Integer(), nullable=False),
        sa.Column("special_requests", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Float(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_1", sa.Integer(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_2", sa.Integer(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_3", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_1", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_2", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_3", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_4", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_5", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_6", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_7", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_online", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_corporate", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_complementary", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_aviation", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_nov", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_dec", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jun", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jan", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_oct", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_may", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_apr", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_aug", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_mar", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_feb", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jul", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_monday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_friday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_wednesday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_thursday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_saturday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_tuesday", sa.Integer(), nullable=False),
        sa.Column("is_cancellation", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    op.create_table(
        "validation_test_data",
        sa.Column("booking_id", sa.String(), nullable=False),
        sa.Column("number_of_adults", sa.Integer(), nullable=False),
        sa.Column("number_of_children", sa.Integer(), nullable=False),
        sa.Column("number_of_weekend_nights", sa.Integer(), nullable=False),
        sa.Column("number_of_week_nights", sa.Integer(), nullable=False),
        sa.Column("lead_time", sa.Integer(), nullable=False),
        sa.Column("car_parking_space", sa.Integer(), nullable=False),
        sa.Column("is_repeat_guest", sa.Integer(), nullable=False),
        sa.Column("num_previous_cancellations", sa.Integer(), nullable=False),
        sa.Column("num_previous_bookings_not_canceled", sa.Integer(), nullable=False),
        sa.Column("special_requests", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Float(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_1", sa.Integer(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_2", sa.Integer(), nullable=False),
        sa.Column("is_type_of_meal_meal_plan_3", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_1", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_2", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_3", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_4", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_5", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_6", sa.Integer(), nullable=False),
        sa.Column("is_room_type_room_type_7", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_online", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_corporate", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_complementary", sa.Integer(), nullable=False),
        sa.Column("is_market_segment_type_aviation", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_nov", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_dec", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jun", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jan", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_oct", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_may", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_apr", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_aug", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_mar", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_feb", sa.Integer(), nullable=False),
        sa.Column("is_month_of_reservation_jul", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_monday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_friday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_wednesday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_thursday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_saturday", sa.Integer(), nullable=False),
        sa.Column("is_day_of_week_tuesday", sa.Integer(), nullable=False),
        sa.Column("is_cancellation", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validation_test_data")
    op.drop_table("train_data")
    # ### end Alembic commands ###
