#!/bin/bash

echo "Writing .env from GitHub Secrets..."

cat <<EOF > .env
KAGGLE_USERNAME=$KAGGLE_USERNAME
KAGGLE_KEY=$KAGGLE_KEY
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_PORT=$DB_PORT
BRONZE_DB_HOST=$BRONZE_DB_HOST
BRONZE_DB=$BRONZE_DB
SILVER_DB_HOST=$SILVER_DB_HOST
SILVER_DB=$SILVER_DB
GOLD_DB_HOST=$GOLD_DB_HOST
GOLD_DB=$GOLD_DB
MLFLOW_DB_HOST=$MLFLOW_DB_HOST
MLFLOW_DB=$MLFLOW_DB
MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
TEST_DB_USER=$TEST_DB_USER
TEST_DB_PASSWORD=$TEST_DB_PASSWORD
TEST_DB_HOST=$TEST_DB_HOST
TEST_DB=$TEST_DB
TEST_DB_PORT=$TEST_DB_PORT
EOF

echo "✅ .env created"
