name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with Ruff, Black, and MyPy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Make setup_env.sh executable
        run: chmod +x scripts/setup_env.sh

      - name: Create .env file
        run: ./scripts/setup_env.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks with CI config (no auto-fix)
        run: pre-commit run --all-files --config .pre-commit-config-ci.yaml

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Make setup_env.sh executable
        run: chmod +x scripts/setup_env.sh

      - name: Create .env file
        run: ./scripts/setup_env.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and code coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=html
